"""DOCX export engine — five templates.

Templates
---------
default       — Standard document (original behavior preserved exactly).
storyboard    — Scene-card table: Scene # | Title | Narration | Visual Cue.
teacher_guide — Learner content + lined Teaching Notes section per block.
quiz_bank     — Numbered Q&A table extracted from content.
client        — Clean minimal formatting for client delivery.

All functions return a BytesIO buffer (binary DOCX data, seeked to 0).
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from io import BytesIO

from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

_NOW = lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
_BRAND = "Powered by Content AI Studio · AI-Generated eLearning Content"


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _add_md_lines(doc: DocxDocument, text: str) -> None:
    """Parse basic Markdown and add styled paragraphs to doc."""
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            doc.add_paragraph(line)


def _save(doc: DocxDocument) -> BytesIO:
    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def _brand_footer(doc: DocxDocument) -> None:
    doc.add_page_break()
    p = doc.add_paragraph(_BRAND)
    p.style = doc.styles["Subtitle"] if "Subtitle" in [s.name for s in doc.styles] else p.style
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER


# ---------------------------------------------------------------------------
# Template: default  (original behavior — do not change)
# ---------------------------------------------------------------------------

def _default(topic: str, blocks: list[tuple[str, str]]) -> BytesIO:
    doc = DocxDocument()
    doc.add_heading(topic, level=0)
    doc.add_paragraph("Generated by Content AI Studio", style="Subtitle")
    doc.add_paragraph(f"Date: {_NOW()}")
    doc.add_page_break()

    for b_label, b_content in blocks:
        doc.add_heading(b_label, level=1)
        _add_md_lines(doc, b_content)
        doc.add_paragraph("")

    _brand_footer(doc)
    return _save(doc)


# ---------------------------------------------------------------------------
# Template: storyboard
# ---------------------------------------------------------------------------

def _storyboard(topic: str, blocks: list[tuple[str, str]]) -> BytesIO:
    doc = DocxDocument()

    # Landscape page for storyboard
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    section = doc.sections[0]
    section.page_width, section.page_height = section.page_height, section.page_width

    doc.add_heading(f"Storyboard — {topic}", level=0)
    p = doc.add_paragraph(f"Production Export · {_NOW()} · {len(blocks)} scene(s)")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    for i, (lbl, cnt) in enumerate(blocks, 1):
        doc.add_heading(f"Scene {i}: {lbl}", level=1)

        tbl = doc.add_table(rows=2, cols=3)
        tbl.style = "Table Grid"
        tbl.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        hdr_cells = tbl.rows[0].cells
        hdr_cells[0].text = "Scene #"
        hdr_cells[1].text = "Narration / Content"
        hdr_cells[2].text = "Visual Notes / Cue"
        for cell in hdr_cells:
            for para in cell.paragraphs:
                run = para.runs[0] if para.runs else para.add_run(para.text)
                run.bold = True

        # Content row
        data_cells = tbl.rows[1].cells
        data_cells[0].text = str(i)
        data_cells[1].text = cnt.strip()
        data_cells[2].text = "[ Visual / animation description ]"

        tbl.columns[0].width = Inches(0.8)
        tbl.columns[1].width = Inches(5.0)
        tbl.columns[2].width = Inches(2.8)

        doc.add_paragraph("")

    _brand_footer(doc)
    return _save(doc)


# ---------------------------------------------------------------------------
# Template: teacher_guide
# ---------------------------------------------------------------------------

def _teacher_guide(topic: str, blocks: list[tuple[str, str]]) -> BytesIO:
    doc = DocxDocument()
    doc.add_heading(f"Teacher Guide — {topic}", level=0)
    doc.add_paragraph("INSTRUCTOR COPY — Not for distribution to learners", style="Subtitle")
    doc.add_paragraph(f"Date: {_NOW()}")
    doc.add_page_break()

    for lbl, cnt in blocks:
        doc.add_heading(lbl, level=1)

        # Learner content
        _add_md_lines(doc, cnt)
        doc.add_paragraph("")

        # Teaching notes box (shaded)
        doc.add_heading("Teaching Notes", level=3)
        p_note = doc.add_paragraph("Instructor notes for this section:")
        p_note.runs[0].italic = True
        p_note.runs[0].font.color.rgb = RGBColor(0x92, 0x40, 0x0E)

        for _ in range(4):
            p = doc.add_paragraph("_" * 80)
            p.runs[0].font.color.rgb = RGBColor(0xD9, 0x77, 0x06)

        doc.add_paragraph("")

    _brand_footer(doc)
    return _save(doc)


# ---------------------------------------------------------------------------
# Template: quiz_bank
# ---------------------------------------------------------------------------

_Q_RE = re.compile(r"^(\d+[\.\)]\s+|Q\d*[\.:]\s*|Question\s*\d*[\.:]\s*)", re.I)


def _quiz_bank(topic: str, blocks: list[tuple[str, str]]) -> BytesIO:
    doc = DocxDocument()
    doc.add_heading(f"Quiz Bank — {topic}", level=0)
    doc.add_paragraph(f"Question Bank Export · {_NOW()}")
    doc.add_page_break()

    questions: list[str] = []
    for _lbl, cnt in blocks:
        for line in cnt.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if _Q_RE.match(stripped) or stripped.endswith("?"):
                questions.append(_Q_RE.sub("", stripped).strip())

    if questions:
        doc.add_heading(f"Questions ({len(questions)} total)", level=1)
        tbl = doc.add_table(rows=1 + len(questions), cols=2)
        tbl.style = "Table Grid"

        # Header
        hdr = tbl.rows[0].cells
        hdr[0].text = "Q #"
        hdr[1].text = "Question"
        for cell in hdr:
            for para in cell.paragraphs:
                run = para.runs[0] if para.runs else para.add_run(para.text)
                run.bold = True

        for i, q in enumerate(questions, 1):
            row = tbl.rows[i].cells
            row[0].text = str(i)
            row[1].text = q

        tbl.columns[0].width = Inches(0.6)
        tbl.columns[1].width = Inches(6.0)
    else:
        doc.add_paragraph(
            "No quiz questions detected. Ensure blocks contain numbered questions "
            "or sentences ending with '?'."
        )

    _brand_footer(doc)
    return _save(doc)


# ---------------------------------------------------------------------------
# Template: client
# ---------------------------------------------------------------------------

def _client(topic: str, blocks: list[tuple[str, str]]) -> BytesIO:
    doc = DocxDocument()

    # Cover
    doc.add_heading(topic, level=0)
    p_sub = doc.add_paragraph("Prepared for Client Review")
    p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_date = doc.add_paragraph(_NOW())
    p_date.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    for lbl, cnt in blocks:
        doc.add_heading(lbl, level=1)
        _add_md_lines(doc, cnt)
        doc.add_paragraph("")

    # Clean footer
    doc.add_page_break()
    p = doc.add_paragraph("Confidential — Prepared for Client Review")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)

    return _save(doc)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

TEMPLATES = {
    "default":       _default,
    "storyboard":    _storyboard,
    "teacher_guide": _teacher_guide,
    "quiz_bank":     _quiz_bank,
    "client":        _client,
}


def build_docx(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> BytesIO:
    """Build a DOCX document for the given template.

    ``blocks`` is a list of (label, content) string tuples.
    Returns a seeked BytesIO buffer ready for download.
    Falls back to "default" for unknown template names.
    """
    fn = TEMPLATES.get(template, _default)
    return fn(topic, blocks)
