"""HTML export engine — five templates.

Templates
---------
default       — Standard styled course document (original behavior).
storyboard    — Scene-card layout for video/animation production teams.
teacher_guide — Learner content + instructor Teaching Notes box per block.
quiz_bank     — Q&A-only extraction for assessment teams.
client        — Clean minimal layout for client delivery.

All functions return a str (complete HTML document).
"""

from __future__ import annotations

from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Shared CSS blocks
# ---------------------------------------------------------------------------

_BASE_CSS = """
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 960px; margin: 50px auto; padding: 0 24px;
    line-height: 1.8; color: #1e293b; background: #fafbfc;
  }
  h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
  h2 { color: #1e40af; margin-top: 2rem; }
  h3 { color: #334155; }
  section { margin-bottom: 2.5rem; }
  hr  { border: none; border-top: 1px solid #e2e8f0; margin: 2rem 0; }
  .footer { text-align: center; color: #94a3b8; font-size: 0.82rem;
            margin-top: 3rem; padding: 1rem; border-top: 1px solid #e2e8f0; }
  .meta  { color: #64748b; font-size: 0.85rem; margin-bottom: 1.5rem; }
"""

_BRAND_FOOTER = "Powered by Content AI Studio · AI-Generated eLearning Content"

_NOW = lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _wrap(title: str, css: str, body: str, meta: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>{css}</style>
</head>
<body>
  <h1>📚 {title}</h1>
  {f'<p class="meta">{meta}</p>' if meta else ""}
  {body}
  <div class="footer">{_BRAND_FOOTER}</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Template: default
# ---------------------------------------------------------------------------

def _default(topic: str, blocks: list[tuple[str, str]]) -> str:
    sections = "".join(
        f"<section><h2>{lbl}</h2><div>{cnt.replace(chr(10), '<br>')}</div></section><hr/>"
        for lbl, cnt in blocks
    )
    return _wrap(topic, _BASE_CSS, sections,
                 meta=f"Generated by Content AI Studio · {_NOW()}")


# ---------------------------------------------------------------------------
# Template: storyboard
# ---------------------------------------------------------------------------

_STORYBOARD_CSS = _BASE_CSS + """
  .scene-card {
    border: 2px solid #e2e8f0; border-radius: 12px;
    padding: 20px 24px; margin-bottom: 1.5rem;
    background: #fff; box-shadow: 0 1px 4px rgba(0,0,0,.06);
  }
  .scene-header {
    display: flex; align-items: center; gap: 12px; margin-bottom: 12px;
  }
  .scene-num {
    background: #2563eb; color: #fff; border-radius: 50%;
    width: 2rem; height: 2rem; display: flex; align-items: center;
    justify-content: center; font-weight: 700; flex-shrink: 0;
  }
  .scene-title { font-weight: 700; font-size: 1.05rem; color: #1e293b; }
  .narration   { margin-bottom: 12px; }
  .visual-notes {
    background: #f8fafc; border-left: 4px solid #2563eb;
    padding: 10px 14px; color: #475569; font-size: 0.88rem;
    border-radius: 0 8px 8px 0;
  }
  .visual-notes strong { color: #1e40af; }
"""


def _storyboard(topic: str, blocks: list[tuple[str, str]]) -> str:
    cards = ""
    for i, (lbl, cnt) in enumerate(blocks, 1):
        cards += f"""
<div class="scene-card">
  <div class="scene-header">
    <div class="scene-num">{i}</div>
    <div class="scene-title">{lbl}</div>
  </div>
  <div class="narration">{cnt.replace(chr(10), '<br>')}</div>
  <div class="visual-notes">
    <strong>Visual Notes / Cue:</strong><br>
    <em>[ Production team: describe visual, animation, or on-screen element here ]</em>
  </div>
</div>"""
    return _wrap(
        f"Storyboard — {topic}", _STORYBOARD_CSS, cards,
        meta=f"Storyboard Export · {_NOW()} · {len(blocks)} scene(s)",
    )


# ---------------------------------------------------------------------------
# Template: teacher_guide
# ---------------------------------------------------------------------------

_TEACHER_CSS = _BASE_CSS + """
  .block-content { margin-bottom: 1rem; }
  .teaching-notes {
    background: #fffbeb; border: 1px dashed #fbbf24;
    border-radius: 8px; padding: 14px 18px; margin-top: 12px;
  }
  .teaching-notes h4 { color: #92400e; margin: 0 0 8px; font-size: 0.9rem; }
  .note-line {
    border-bottom: 1px dotted #d97706; height: 1.6rem; margin-bottom: 4px;
  }
"""


def _teacher_guide(topic: str, blocks: list[tuple[str, str]]) -> str:
    sections = ""
    for lbl, cnt in blocks:
        note_lines = "".join('<div class="note-line"></div>' for _ in range(4))
        sections += f"""
<section>
  <h2>{lbl}</h2>
  <div class="block-content">{cnt.replace(chr(10), '<br>')}</div>
  <div class="teaching-notes">
    <h4>🖊 Instructor Teaching Notes</h4>
    {note_lines}
  </div>
</section><hr/>"""
    return _wrap(
        f"Teacher Guide — {topic}", _TEACHER_CSS, sections,
        meta=f"Instructor Copy · Not for Distribution to Learners · {_NOW()}",
    )


# ---------------------------------------------------------------------------
# Template: quiz_bank
# ---------------------------------------------------------------------------

_QUIZ_CSS = _BASE_CSS + """
  .q-item { margin-bottom: 1.5rem; }
  .q-num  { font-weight: 700; color: #2563eb; }
  .answer-space {
    border: 1px solid #cbd5e1; border-radius: 6px;
    height: 60px; margin-top: 8px; background: #f8fafc;
  }
"""

_QUIZ_BLOCK_TYPES = frozenset({"quiz", "assessment", "test", "exam"})


def _quiz_bank(topic: str, blocks: list[tuple[str, str]]) -> str:
    import re
    q_items = ""
    q_num = 0
    _q_re = re.compile(r"^(\d+[\.\)]\s+|Q\d*[\.:]\s*|Question\s*\d*[\.:]\s*)", re.I)

    for lbl, cnt in blocks:
        # Include all blocks — let quiz items self-identify
        for line in cnt.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if _q_re.match(stripped) or stripped.endswith("?"):
                q_num += 1
                text = _q_re.sub("", stripped).strip()
                q_items += f"""
<div class="q-item">
  <div><span class="q-num">Q{q_num}.</span> {text}</div>
  <div class="answer-space"></div>
</div>"""

    if not q_items:
        q_items = "<p><em>No quiz questions detected. Ensure blocks contain numbered questions or sentences ending with '?'.</em></p>"

    body = f"<p><strong>Total questions extracted: {q_num}</strong></p>{q_items}"
    return _wrap(
        f"Quiz Bank — {topic}", _QUIZ_CSS, body,
        meta=f"Question Bank Export · {_NOW()} · {q_num} question(s)",
    )


# ---------------------------------------------------------------------------
# Template: client
# ---------------------------------------------------------------------------

_CLIENT_CSS = """
  body {
    font-family: 'Georgia', 'Times New Roman', serif;
    max-width: 860px; margin: 60px auto; padding: 0 32px;
    line-height: 1.9; color: #111827; background: #fff;
  }
  h1 { color: #111827; border-bottom: 2px solid #111827; padding-bottom: 8px;
       font-size: 1.8rem; }
  h2 { color: #1f2937; font-size: 1.2rem; margin-top: 2.5rem;
       text-transform: uppercase; letter-spacing: .06em; }
  section { margin-bottom: 3rem; }
  hr  { border: none; border-top: 1px solid #d1d5db; margin: 2.5rem 0; }
  .footer { text-align: center; color: #9ca3af; font-size: 0.78rem;
            margin-top: 4rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; }
  .cover  { text-align: center; margin-bottom: 4rem; }
  .cover p { color: #6b7280; font-size: 0.95rem; }
"""


def _client(topic: str, blocks: list[tuple[str, str]]) -> str:
    sections = "".join(
        f"<section><h2>{lbl}</h2><p>{cnt.replace(chr(10), '</p><p>')}</p></section><hr/>"
        for lbl, cnt in blocks
    )
    cover = f'<div class="cover"><h1>{topic}</h1><p>Prepared for Client Review</p><p>{_NOW()}</p></div>'
    return _wrap(topic, _CLIENT_CSS, cover + sections)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

TEMPLATES = {
    "default":       _default,
    "storyboard":    _storyboard,
    "teacher_guide": _teacher_guide,
    "quiz_bank":     _quiz_bank,
    "client":        _client,
}


def build_html(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> str:
    """Build a complete HTML document for the given template.

    ``blocks`` is a list of (label, content) string tuples.
    Falls back to "default" for unknown template names.
    """
    fn = TEMPLATES.get(template, _default)
    return fn(topic, blocks)
