"""PDF export engine — the same five templates the DOCX exporter offers.

Requires ``reportlab``. It is a declared dependency (requirements.txt /
pyproject.toml); the ImportError branch below stays only so a broken
environment produces ``ExportUnsupportedError`` — which export_service turns
into a clean ExportResult — rather than a 500.

The template set and each template's intent mirror docx_exporter.TEMPLATES
deliberately: a user who picks "Teacher Guide" should get the same document in
either format, not two unrelated layouts. Structure is driven by _SPEC plus a
per-template block renderer, so adding a template is a dict entry and not a
sixth copy of the page setup.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from io import BytesIO


class ExportUnsupportedError(RuntimeError):
    """Raised when the required library is not installed."""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# Same question detection as docx_exporter._Q_RE — quiz_bank must find the same
# questions in both formats.
_Q_RE = re.compile(r"^(\d+[\.\)]\s+|Q\d*[\.:]\s*|Question\s*\d*[\.:]\s*)", re.I)

_ACCENT = "#2563eb"
_HEADING = "#1e40af"
_RULE = "#e2e8f0"
_NOTE = "#92400e"
_NOTE_RULE = "#d97706"
_MUTED = "#9ca3af"

#: title_prefix, subtitle, landscape, footer. `None` footer = the brand footer.
_SPEC: dict[str, dict] = {
    "default": {
        "title": "{topic}",
        "subtitle": "Generated by Content AI Studio",
        "landscape": False,
        "footer": None,
    },
    "storyboard": {
        "title": "Storyboard — {topic}",
        "subtitle": "Production Export · {now} · {count} scene(s)",
        "landscape": True,
        "footer": None,
    },
    "teacher_guide": {
        "title": "Teacher Guide — {topic}",
        "subtitle": "INSTRUCTOR COPY — Not for distribution to learners",
        "landscape": False,
        "footer": None,
    },
    "quiz_bank": {
        "title": "Quiz Bank — {topic}",
        "subtitle": "Question Bank Export · {now}",
        "landscape": False,
        "footer": None,
    },
    "client": {
        "title": "{topic}",
        "subtitle": "Prepared for Client Review",
        "landscape": False,
        "footer": "Confidential — Prepared for Client Review",
    },
}

_BRAND_FOOTER = "Powered by Content AI Studio · AI-Generated eLearning Content"


def _escape(text: str) -> str:
    """reportlab Paragraph parses its input as mini-HTML, so raw content
    containing <, > or & raises or silently swallows text. Content comes from
    an LLM and routinely contains all three."""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_pdf(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> BytesIO:
    """Generate a PDF for *template*.

    Unknown template names fall back to "default", matching
    ``docx_exporter.build_docx``. Raises ExportUnsupportedError if reportlab is
    not installed.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            HRFlowable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )
    except ImportError as exc:
        raise ExportUnsupportedError(
            "PDF generation requires the 'reportlab' library. "
            "Install it with: pip install reportlab"
        ) from exc

    spec = _SPEC.get(template) or _SPEC["default"]
    name = template if template in _SPEC else "default"

    buf = BytesIO()
    pagesize = landscape(A4) if spec["landscape"] else A4
    doc = SimpleDocTemplate(
        buf,
        pagesize=pagesize,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm,
        topMargin=2.5 * cm, bottomMargin=2.5 * cm,
        title=topic,
    )
    frame_width = pagesize[0] - 5 * cm

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle", parent=styles["Title"], fontSize=20,
        textColor=colors.HexColor(_ACCENT), spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "BlockTitle", parent=styles["Heading1"], fontSize=14,
        textColor=colors.HexColor(_HEADING), spaceBefore=16, spaceAfter=6,
    )
    body_style = ParagraphStyle("DocBody", parent=styles["Normal"], leading=18)
    cell_style = ParagraphStyle("Cell", parent=body_style, fontSize=9, leading=12)
    centred = ParagraphStyle("Centred", parent=styles["Italic"], alignment=TA_CENTER)

    def md_lines(text: str) -> list:
        out = []
        for line in str(text).splitlines():
            line = line.strip()
            if not line:
                out.append(Spacer(1, 0.2 * cm))
                continue
            out.append(Paragraph(_escape(line), body_style))
        return out

    def grid(data, widths) -> Table:
        t = Table(
            data,
            colWidths=widths,
            repeatRows=1,
            splitByRow=1,
            splitInRow=1,
        )
        t.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor(_RULE)),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return t

    # ── Cover ─────────────────────────────────────────────────────────
    story: list = [
        Paragraph(_escape(spec["title"].format(topic=topic)), title_style),
        Paragraph(
            _escape(spec["subtitle"].format(topic=topic, now=_now(), count=len(blocks))),
            centred if name in ("storyboard", "client") else styles["Italic"],
        ),
        Paragraph(f"Date: {_now()}", centred if name == "client" else styles["Italic"]),
        PageBreak(),
    ]

    # ── Body ──────────────────────────────────────────────────────────
    if name == "storyboard":
        # Scene table per block: the DOCX storyboard's three columns.
        for i, (lbl, cnt) in enumerate(blocks, 1):
            story.append(Paragraph(_escape(f"Scene {i}: {lbl}"), heading_style))
            story.append(grid(
                [["Scene #", "Narration / Content", "Visual Notes / Cue"],
                 [str(i),
                  Paragraph(_escape(str(cnt).strip()), cell_style),
                  Paragraph("[ Visual / animation description ]", cell_style)]],
                [0.08 * frame_width, 0.57 * frame_width, 0.35 * frame_width],
            ))
            story.append(Spacer(1, 0.4 * cm))

    elif name == "quiz_bank":
        questions: list[str] = []
        for _lbl, cnt in blocks:
            for line in str(cnt).splitlines():
                s = line.strip()
                if s and (_Q_RE.match(s) or s.endswith("?")):
                    questions.append(_Q_RE.sub("", s).strip())
        if questions:
            story.append(Paragraph(f"Questions ({len(questions)} total)", heading_style))
            rows = [["Q #", "Question"]]
            rows += [[str(i), Paragraph(_escape(q), cell_style)]
                     for i, q in enumerate(questions, 1)]
            story.append(grid(rows, [0.09 * frame_width, 0.91 * frame_width]))
        else:
            story.append(Paragraph(
                "No quiz questions detected. Ensure blocks contain numbered questions "
                "or sentences ending with '?'.", body_style))

    else:
        for lbl, cnt in blocks:
            story.append(Paragraph(_escape(lbl), heading_style))
            story.extend(md_lines(cnt))
            if name == "teacher_guide":
                story.append(Spacer(1, 0.3 * cm))
                story.append(Paragraph(
                    "<b>Teaching Notes</b>",
                    ParagraphStyle("NoteHead", parent=body_style,
                                   textColor=colors.HexColor(_NOTE)),
                ))
                story.append(Paragraph(
                    "<i>Instructor notes for this section:</i>",
                    ParagraphStyle("NoteBody", parent=body_style,
                                   textColor=colors.HexColor(_NOTE)),
                ))
                for _ in range(4):
                    story.append(Spacer(1, 0.35 * cm))
                    story.append(HRFlowable(width="100%", thickness=0.5,
                                            color=colors.HexColor(_NOTE_RULE)))
                story.append(Spacer(1, 0.3 * cm))
            story.append(HRFlowable(width="100%", color=colors.HexColor(_RULE)))

    # ── Footer ────────────────────────────────────────────────────────
    story.append(PageBreak())
    if spec["footer"]:
        story.append(Paragraph(
            _escape(spec["footer"]),
            ParagraphStyle("Footer", parent=centred, textColor=colors.HexColor(_MUTED)),
        ))
    else:
        story.append(Paragraph(_BRAND_FOOTER, centred))

    doc.build(story)
    buf.seek(0)
    return buf


#: Mirrors docx_exporter.TEMPLATES so callers can ask what PDF supports.
TEMPLATES = tuple(_SPEC)
