"""PDF export engine.

Strategy: attempt reportlab for full PDF generation. If reportlab is not installed,
fall back to returning the HTML bytes so the caller can present a graceful error
or offer HTML as an alternative.

Install reportlab to enable PDF:
    pip install reportlab

The caller (export_service.py) catches ExportUnsupportedError and presents a
user-friendly message rather than crashing the application.
"""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO


class ExportUnsupportedError(RuntimeError):
    """Raised when the required library is not installed."""


def build_pdf(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> BytesIO:
    """Generate a PDF document.

    Requires ``reportlab``. Raises ExportUnsupportedError if not installed.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, PageBreak, HRFlowable,
        )
    except ImportError:
        raise ExportUnsupportedError(
            "PDF generation requires the 'reportlab' library. "
            "Install it with: pip install reportlab"
        )

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm,
        topMargin=2.5 * cm, bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#2563eb"),
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "BlockTitle",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=colors.HexColor("#1e40af"),
        spaceBefore=16,
        spaceAfter=6,
    )
    body_style = styles["Normal"]
    body_style.leading = 18

    story = []
    story.append(Paragraph(f"📚 {topic}", title_style))
    story.append(Paragraph(
        f"Generated by Content AI Studio · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"],
    ))
    story.append(Spacer(1, 0.5 * cm))

    for lbl, cnt in blocks:
        story.append(Paragraph(lbl, heading_style))
        for line in cnt.splitlines():
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.2 * cm))
                continue
            story.append(Paragraph(line, body_style))
        story.append(HRFlowable(width="100%", color=colors.HexColor("#e2e8f0")))

    story.append(PageBreak())
    story.append(Paragraph(
        "Powered by Content AI Studio · AI-Generated eLearning Content",
        styles["Italic"],
    ))

    doc.build(story)
    buf.seek(0)
    return buf
