"""XLSX export engine — single-sheet "Section | Content" layout.

Produces one worksheet with two columns: the section label and its full
(Markdown) content, one row per block. Mirrors the block model used by the
other exporters — ``blocks`` is a list of (label, content) string tuples.

Returns a BytesIO buffer (binary XLSX data, seeked to 0).
"""

from __future__ import annotations

import re as _re
from datetime import datetime, timezone
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

_NOW = lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
_BRAND = "Powered by Content AI Studio · AI-Generated eLearning Content"

# Styling constants
_HEADER_FILL = PatternFill("solid", fgColor="4F46E5")   # indigo, matches app accent
_HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
_TITLE_FONT = Font(bold=True, size=16)
_META_FONT = Font(italic=True, size=9, color="6B7280")
_BRAND_FONT = Font(italic=True, size=9, color="9CA3AF")
_WRAP_TOP = Alignment(wrap_text=True, vertical="top")

_SECTION_COL_WIDTH = 32
_CONTENT_COL_WIDTH = 100


def build_xlsx(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> BytesIO:
    """Build a single-sheet XLSX workbook for the given blocks.

    ``blocks`` is a list of (label, content) string tuples.
    ``template`` is accepted for signature parity with the other exporters
    but does not change the single-sheet layout.
    Returns a seeked BytesIO buffer ready for download.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Content"

    # Row 1 — document title
    ws["A1"] = topic or "Export"
    ws["A1"].font = _TITLE_FONT
    ws.merge_cells("A1:B1")

    # Row 2 — generated-by metadata
    ws["A2"] = f"Generated by Content AI Studio · {_NOW()}"
    ws["A2"].font = _META_FONT
    ws.merge_cells("A2:B2")

    # Row 4 — column headers ("Section" | "Content")
    header_row = 4
    headers = ["Section", "Content"]
    for col_idx, label in enumerate(headers, start=1):
        cell = ws.cell(row=header_row, column=col_idx, value=label)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(vertical="center")

    # Data rows — one per block
    row = header_row + 1
    for lbl, cnt in blocks:
        section_cell = ws.cell(row=row, column=1, value=lbl)
        section_cell.alignment = _WRAP_TOP
        section_cell.font = Font(bold=True)

        content_cell = ws.cell(row=row, column=2, value=(cnt or "").strip())
        content_cell.alignment = _WRAP_TOP
        row += 1

    # Brand footer — one blank row below the table
    ws.cell(row=row + 1, column=1, value=_BRAND).font = _BRAND_FONT

    # Column widths + freeze header so it stays visible while scrolling
    ws.column_dimensions[get_column_letter(1)].width = _SECTION_COL_WIDTH
    ws.column_dimensions[get_column_letter(2)].width = _CONTENT_COL_WIDTH
    ws.freeze_panes = f"A{header_row + 1}"

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Multi-sheet export (DLU CDD) — one sheet per worksheet
# ---------------------------------------------------------------------------

_ILLEGAL_SHEET_CHARS = _re.compile(r"[\\/?*\[\]:]")
_TABLE_SEP_CELL = _re.compile(r"^:?-{2,}:?$")
# "- **Label:** value" — the key-value bullet shape emitted by
# block_wide_service._fields_section for the Block Overview and Patterns &
# Design Notes worksheets. Captured so it can be split into label/value cells
# rather than written as raw markdown into a single cell. The value is optional
# (a field with no data renders as "- **Label:** ").
_KV_BULLET = _re.compile(r"^[-*]\s+\*\*(.+?):\*\*\s*(.*)$")


def _safe_sheet_name(base: str, used: set) -> str:
    """Excel-safe, unique sheet name (<=31 chars, no \\ / ? * [ ] : chars).

    Truncates at a word boundary so names don't end mid-word.
    """
    name = _ILLEGAL_SHEET_CHARS.sub(" ", base or "Sheet").strip()
    name = _re.sub(r"\s+", " ", name)
    if len(name) > 31:
        cut = name[:31]
        sp = cut.rfind(" ")
        name = (cut[:sp] if sp >= 15 else cut).strip()
    # Excel also rejects sheet names that start or end with a single quote.
    name = name.strip("'").strip() or "Sheet"
    if name in used:
        i = 2
        stem = name[:28]
        while f"{stem} {i}" in used:
            i += 1
        name = f"{stem} {i}"
    return name


def _split_table_row(line: str) -> list[str]:
    cells = line.split("|")
    if cells and cells[0].strip() == "":
        cells = cells[1:]
    if cells and cells[-1].strip() == "":
        cells = cells[:-1]
    return [c.strip() for c in cells]


def _render_section_sheet(ws, topic: str, section_name: str, content: str) -> None:
    """Render one worksheet's markdown into a sheet: markdown tables become real
    cell grids; headings become bold rows; prose/bullets become wrapped rows."""
    ws["A1"] = section_name or "Worksheet"
    ws["A1"].font = _TITLE_FONT
    ws.merge_cells("A1:E1")
    ws["A2"] = f"{topic or 'CDD'} · Generated by Content AI Studio · {_NOW()}"
    ws["A2"].font = _META_FONT
    ws.merge_cells("A2:E2")

    row = 4
    max_cols = 1
    lines = (content or "").split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith("|"):
            # ── markdown table block → real cells ──────────────────────────
            first_data = True
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = _split_table_row(lines[i])
                i += 1
                if cells and all(_TABLE_SEP_CELL.match(c or "") for c in cells):
                    continue  # separator row
                for c_idx, val in enumerate(cells, start=1):
                    cell = ws.cell(row=row, column=c_idx, value=val)
                    cell.alignment = _WRAP_TOP
                    if first_data:
                        cell.font = _HEADER_FONT
                        cell.fill = _HEADER_FILL
                max_cols = max(max_cols, len(cells))
                first_data = False
                row += 1
            row += 1  # blank spacer after a table
            continue

        stripped = line.strip()
        if stripped == "":
            i += 1
            continue

        # ── "- **Label:** value" bullet → two real cells ────────────────────
        # The key-value worksheets (Block Overview, Patterns & Design Notes) are
        # emitted as markdown bullets by block_wide_service._fields_section. Written
        # verbatim they land as one string in column A ("- **Block:** Block 2"),
        # which is unusable as a spreadsheet and does not match the AIM reference —
        # whose Block Overview is a plain two-column label/value grid. Split them so
        # the label is a bold column-A cell and the value is column B, matching the
        # reference layout and making the fields readable/filterable.
        kv = _KV_BULLET.match(stripped)
        if kv:
            label = ws.cell(row=row, column=1, value=kv.group(1).strip())
            label.font = _HEADER_FONT
            label.alignment = _WRAP_TOP
            value = ws.cell(row=row, column=2, value=kv.group(2).strip())
            value.alignment = _WRAP_TOP
            max_cols = max(max_cols, 2)
            row += 1
            i += 1
            continue

        heading = _re.match(r"^(#{1,6})\s+(.*)$", stripped)
        cell = ws.cell(row=row, column=1)
        if heading:
            cell.value = heading.group(2).strip()
            cell.font = Font(bold=True, size=13 if len(heading.group(1)) <= 2 else 11)
        else:
            # Plain bullet with no bold label — strip the markdown marker so the
            # cell reads as content, not as raw markdown.
            cell.value = _re.sub(r"^[-*]\s+", "", stripped)
        cell.alignment = _WRAP_TOP
        row += 1
        i += 1

    ws.cell(row=row + 1, column=1, value=_BRAND).font = _BRAND_FONT

    # Column widths: first column wide for prose + a table's first column;
    # remaining columns sized for table data.
    ws.column_dimensions[get_column_letter(1)].width = 46
    for c in range(2, max(max_cols, 1) + 1):
        ws.column_dimensions[get_column_letter(c)].width = 26
    ws.freeze_panes = "A4"


def build_xlsx_worksheets(topic: str, sheets: list[tuple[str, str]]) -> BytesIO:
    """Build a multi-sheet XLSX — one sheet per (name, content) section.

    Used for DLU CDDs so each worksheet (Overview + Worksheet 1..N) lands on its
    own sheet. Falls back to the single-sheet layout if ``sheets`` is empty.
    Returns a seeked BytesIO buffer ready for download.
    """
    if not sheets:
        return build_xlsx(topic, [])

    wb = Workbook()
    used: set = set()
    for idx, (name, content) in enumerate(sheets):
        sheet_name = _safe_sheet_name(name, used)
        used.add(sheet_name)
        ws = wb.active if idx == 0 else wb.create_sheet()
        ws.title = sheet_name
        _render_section_sheet(ws, topic, name, content)

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
