"""XLSX export engine — single-sheet "Section | Content" layout.

Produces one worksheet with two columns: the section label and its full
(Markdown) content, one row per block. Mirrors the block model used by the
other exporters — ``blocks`` is a list of (label, content) string tuples.

Returns a BytesIO buffer (binary XLSX data, seeked to 0).
"""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

_NOW = lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
_BRAND = "Powered by Content AI Studio · AI-Generated eLearning Content"

# Styling constants
_HEADER_FILL = PatternFill("solid", fgColor="4F46E5")   # indigo, matches app accent
_HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
_TITLE_FONT = Font(bold=True, size=16)
_META_FONT = Font(italic=True, size=9, color="6B7280")
_BRAND_FONT = Font(italic=True, size=9, color="9CA3AF")
_WRAP_TOP = Alignment(wrap_text=True, vertical="top")

_SECTION_COL_WIDTH = 32
_CONTENT_COL_WIDTH = 100


def build_xlsx(topic: str, blocks: list[tuple[str, str]], template: str = "default") -> BytesIO:
    """Build a single-sheet XLSX workbook for the given blocks.

    ``blocks`` is a list of (label, content) string tuples.
    ``template`` is accepted for signature parity with the other exporters
    but does not change the single-sheet layout.
    Returns a seeked BytesIO buffer ready for download.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Content"

    # Row 1 — document title
    ws["A1"] = topic or "Export"
    ws["A1"].font = _TITLE_FONT
    ws.merge_cells("A1:B1")

    # Row 2 — generated-by metadata
    ws["A2"] = f"Generated by Content AI Studio · {_NOW()}"
    ws["A2"].font = _META_FONT
    ws.merge_cells("A2:B2")

    # Row 4 — column headers ("Section" | "Content")
    header_row = 4
    headers = ["Section", "Content"]
    for col_idx, label in enumerate(headers, start=1):
        cell = ws.cell(row=header_row, column=col_idx, value=label)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(vertical="center")

    # Data rows — one per block
    row = header_row + 1
    for lbl, cnt in blocks:
        section_cell = ws.cell(row=row, column=1, value=lbl)
        section_cell.alignment = _WRAP_TOP
        section_cell.font = Font(bold=True)

        content_cell = ws.cell(row=row, column=2, value=(cnt or "").strip())
        content_cell.alignment = _WRAP_TOP
        row += 1

    # Brand footer — one blank row below the table
    ws.cell(row=row + 1, column=1, value=_BRAND).font = _BRAND_FONT

    # Column widths + freeze header so it stays visible while scrolling
    ws.column_dimensions[get_column_letter(1)].width = _SECTION_COL_WIDTH
    ws.column_dimensions[get_column_letter(2)].width = _CONTENT_COL_WIDTH
    ws.freeze_panes = f"A{header_row + 1}"

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
