"""Inline Prompt Controls — placed near each component's Generate button.

Renders a compact, fully-featured prompt section that replaces the separate
Prompt Settings + Additional Instructions expanders with a single inline panel:

    ┌──────────────────────────────────────────────────────────────────┐
    │  🎯 Prompt Configuration                                         │
    │  Prompt Template: [🏷️ Default CDD Prompt ▼]                     │
    │  📦 default_cdd_prompt · version: v2 · updated: 2026-05-06      │
    │                                                                  │
    │  💬 Additional Instructions (optional)                           │
    │  Load saved: [dropdown ▼]  [📥 Load]                            │
    │  [textarea]                                                      │
    │                                                                  │
    │  [➕ New Prompt] [✏️ Edit] [🤖 Improve] [💾 Save] [⬇️ Download]  │
    └──────────────────────────────────────────────────────────────────┘

Usage (outside any st.form):

    sys_p, usr_p, extra = render_inline_prompt_controls(
        db, "cdd",
        project_id=_proj_id, cluster_id=None, course_id=_crs_id,
        user_name=user_name, model_choice=model_choice,
        default_system=CDD_SYSTEM_PROMPT,
        default_user=CDD_USER_PROMPT_TEMPLATE,
    )
    # sys_p / usr_p are the active prompt texts; extra is the user's instructions.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Optional

import streamlit as st

from promptops_app.database import Prompt, PromptVersion
from promptops_app.repositories import prompt_repository
from promptops_app.repositories.user_prompt_history_repository import (
    list_latest_for_component,
    save_prompt as _save_instr,
    soft_delete as _del_instr,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_COMP_LABELS = {
    "style":     "Style",
    "cdd":       "CDD",
    "blueprint": "Blueprint",
    "generate":  "Generate",
}


# ---------------------------------------------------------------------------
# Prompt markdown builder
# ---------------------------------------------------------------------------

def _build_prompt_md(
    *,
    project_name: str,
    cluster_name: str,
    course_name: str,
    component: str,
    prompt_name: str,
    prompt_version: str,
    system_prompt: str,
    user_prompt_template: str,
    extra_instructions: str,
    is_ai_override: bool = False,
) -> str:
    """Build a Markdown-formatted prompt download string with full context metadata."""
    from datetime import datetime, timezone
    ts          = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    comp_label  = _COMP_LABELS.get(component, component.title())
    ver_display = f"{prompt_version}" + (" *(AI-improved — not saved)*" if is_ai_override else "")

    lines = [
        f"# Prompt Download — {comp_label}",
        f"",
        f"> **Downloaded:** {ts}",
        f"",
        f"---",
        f"",
        f"## Context",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Project** | {project_name or '—'} |",
    ]
    if cluster_name:
        lines.append(f"| **Cluster** | {cluster_name} |")
    if course_name:
        lines.append(f"| **Course** | {course_name} |")
    lines += [
        f"| **Component** | {comp_label} |",
        f"| **Prompt Asset** | {prompt_name or '—'} |",
        f"| **Version** | {ver_display} |",
        f"",
        f"---",
        f"",
        f"## System Prompt",
        f"",
        system_prompt.strip() if system_prompt else "*(none)*",
        f"",
        f"---",
        f"",
        f"## User Prompt Template",
        f"",
        user_prompt_template.strip() if user_prompt_template else "*(none)*",
        f"",
    ]
    if extra_instructions and extra_instructions.strip():
        lines += [
            f"---",
            f"",
            f"## Additional Instructions",
            f"",
            extra_instructions.strip(),
            f"",
        ]
    lines += ["---", "", "*Generated by Content AI Studio*"]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Standalone download button (placed near component content download buttons)
# ---------------------------------------------------------------------------

def render_prompt_download_button(
    db,
    component: str,
    project_name: str = "",
    cluster_name: str = "",
    course_name: str = "",
    button_label: str = "⬇️ Download Prompt Used",
    key: str = "",
    use_container_width: bool = False,
    help_text: str = "Download the prompt used for generation as a Markdown file.",
) -> None:
    """Standalone download button — place near any component's content download buttons.

    Reads the currently-selected prompt from session state (set by
    render_inline_prompt_controls for the same component).
    """
    _PFX      = f"_gc_{component}"
    _SEL_KEY  = f"{_PFX}_sel"
    _EXTRA_KEY = f"{_PFX}_extra"
    _OVRD_SYS = f"{_PFX}_override_sys"
    _OVRD_USR = f"{_PFX}_override_usr"

    sel_label      = st.session_state.get(_SEL_KEY, "")
    extra          = st.session_state.get(_EXTRA_KEY, "")
    override_sys   = st.session_state.get(_OVRD_SYS)
    override_usr   = st.session_state.get(_OVRD_USR)
    is_ai_override = override_sys is not None or override_usr is not None

    prompt_name    = ""
    prompt_version = "—"
    sys_p          = override_sys or ""
    usr_p          = override_usr or ""

    # Look up prompt details from DB when not using an AI override
    _label_map: dict[str, Prompt] = {}
    try:
        for p in prompt_repository.list_prompts_by_component(db, component):
            lbl = _display_label(p)
            if lbl not in _label_map:
                _label_map[lbl] = p
        for p in prompt_repository.list_prompts_tagged(db, component):
            if p.component_type != component:
                lbl = _display_label(p)
                if lbl not in _label_map:
                    _label_map[lbl] = p
    except Exception:
        pass

    _sel_p = _label_map.get(sel_label)
    if _sel_p is None:
        # Fall back to the default prompt for this component
        try:
            _sel_p = prompt_repository.get_default_prompt(db, component)
        except Exception:
            pass

    if _sel_p is not None:
        prompt_name    = _sel_p.name
        prompt_version = _sel_p.active_version or "v1"
        if not sys_p or not usr_p:
            try:
                _ver = prompt_repository.get_active_version(db, _sel_p.id)
                if _ver:
                    sys_p = sys_p or (_ver.system_prompt or "")
                    usr_p = usr_p or (_ver.user_prompt_template or "")
            except Exception:
                pass

    _md = _build_prompt_md(
        project_name=project_name,
        cluster_name=cluster_name,
        course_name=course_name,
        component=component,
        prompt_name=prompt_name,
        prompt_version=prompt_version,
        system_prompt=sys_p,
        user_prompt_template=usr_p,
        extra_instructions=extra,
        is_ai_override=is_ai_override,
    )
    _safe_ver  = (prompt_version or "v1").replace("/", "-").replace(" ", "_")
    _safe_comp = component.lower()
    _fname     = f"prompt_{_safe_comp}_{_safe_ver}.doc"

    st.download_button(
        button_label,
        data=_md,
        file_name=_fname,
        mime="application/msword",
        use_container_width=use_container_width,
        key=key or f"{_PFX}_standalone_dl",
        help=help_text,
    )


def _display_label(p: Prompt) -> str:
    if p.is_default:
        comp = _COMP_LABELS.get(p.component_type or "", p.component_type or "")
        return f"🏷️ Default {comp} Prompt"
    return p.name


# ---------------------------------------------------------------------------
# "View Prompt" modal
# ---------------------------------------------------------------------------

@st.dialog("🔍 Prompt Details", width="large")
def _prompt_viewer_dialog(
    *,
    component: str,
    prompt_name: str,
    prompt_version: str,
    prompt_owner: str,
    prompt_updated,           # datetime | None
    is_default: bool,
    project_name: str,
    cluster_name: str,
    course_name: str,
    system_prompt: str,
    user_prompt: str,
    extra_instructions: str,
    is_ai_override: bool,
    edit_session_key: str,    # session_state key that opens the Edit panel
    dl_md: str,               # pre-built Markdown download string
    dl_filename: str,
) -> None:
    """Read-only full-screen modal showing the complete active prompt.

    Actions
    -------
    ⬇️ Download  — exports the prompt as a Markdown file (pre-built by the caller).
    ✏️ Edit      — sets the inline-edit panel flag and reruns (dialog closes automatically).
    ✕  Close     — dismisses the dialog via st.rerun().
    """
    comp_label = _COMP_LABELS.get(component, component.title())

    # Scope breadcrumb
    _scope_parts: list[str] = []
    if project_name:
        _scope_parts.append(f"Project: <strong>{project_name}</strong>")
    if cluster_name:
        _scope_parts.append(f"Cluster: <strong>{cluster_name}</strong>")
    if course_name:
        _scope_parts.append(f"Course: <strong>{course_name}</strong>")
    _scope_html = " &nbsp;›&nbsp; ".join(_scope_parts) if _scope_parts else "—"

    _updated_str = "—"
    if prompt_updated:
        try:
            _updated_str = prompt_updated.strftime("%Y-%m-%d")
        except Exception:
            pass

    _default_badge = (
        " <span style='background:#eef2ff;color:#4338ca;font-size:0.72rem;"
        "font-weight:700;padding:1px 8px;border-radius:12px;letter-spacing:.04em;'>"
        "default</span>"
        if is_default else ""
    )
    _ai_badge = (
        " <span style='background:#eff6ff;color:#1d4ed8;font-size:0.72rem;"
        "font-weight:700;padding:1px 8px;border-radius:12px;letter-spacing:.04em;'>"
        "AI-improved · not saved</span>"
        if is_ai_override else ""
    )

    # ── Metadata card ─────────────────────────────────────────────────────────
    st.markdown(
        f"<div style='background:#f8faff;border:1.5px solid #c7d2fe;border-radius:12px;"
        f"padding:16px 22px;margin-bottom:20px;'>"
        f"<div style='display:grid;grid-template-columns:110px 1fr;row-gap:10px;"
        f"font-size:0.875rem;align-items:baseline;'>"
        f"<span style='color:#6b7280;font-weight:500;'>Name</span>"
        f"<span style='font-weight:700;color:#111827;'>{prompt_name}{_default_badge}</span>"
        f"<span style='color:#6b7280;font-weight:500;'>Component</span>"
        f"<span style='color:#4f46e5;font-weight:700;'>{comp_label}</span>"
        f"<span style='color:#6b7280;font-weight:500;'>Version</span>"
        f"<span><code style='background:#eef2ff;color:#4338ca;padding:2px 9px;"
        f"border-radius:5px;font-size:0.82rem;font-weight:600;'>{prompt_version}</code>"
        f"{_ai_badge}</span>"
        f"<span style='color:#6b7280;font-weight:500;'>Owner</span>"
        f"<span style='color:#374151;'>{prompt_owner}</span>"
        f"<span style='color:#6b7280;font-weight:500;'>Updated</span>"
        f"<span style='color:#374151;'>{_updated_str}</span>"
        f"<span style='color:#6b7280;font-weight:500;'>Scope</span>"
        f"<span style='color:#374151;font-size:0.83rem;'>{_scope_html}</span>"
        f"</div></div>",
        unsafe_allow_html=True,
    )

    if is_ai_override:
        st.info(
            "🤖 **AI-improved prompt is active.** "
            "The prompts shown here reflect the in-session AI version and have not been saved to the database.",
            icon="🤖",
        )

    # ── System prompt ──────────────────────────────────────────────────────────
    st.markdown(
        "<p style='font-size:0.82rem;font-weight:700;color:#374151;"
        "margin:0 0 4px;'>System Prompt</p>",
        unsafe_allow_html=True,
    )
    st.code(
        system_prompt.strip() if system_prompt and system_prompt.strip() else "(empty)",
        language="text",
        wrap_lines=True,
    )

    # ── User prompt template ───────────────────────────────────────────────────
    st.markdown(
        "<p style='font-size:0.82rem;font-weight:700;color:#374151;"
        "margin:12px 0 4px;'>User Prompt Template</p>",
        unsafe_allow_html=True,
    )
    st.code(
        user_prompt.strip() if user_prompt and user_prompt.strip() else "(empty)",
        language="text",
        wrap_lines=True,
    )

    # ── Additional instructions (only when present) ────────────────────────────
    if extra_instructions and extra_instructions.strip():
        st.markdown(
            "<p style='font-size:0.82rem;font-weight:700;color:#374151;"
            "margin:12px 0 4px;'>Additional Instructions</p>",
            unsafe_allow_html=True,
        )
        st.code(extra_instructions.strip(), language="text", wrap_lines=True)

    st.divider()

    # ── Actions ────────────────────────────────────────────────────────────────
    _ac1, _ac2, _ac3 = st.columns([0.36, 0.36, 0.28])

    _ac1.download_button(
        "⬇️ Download Prompt",
        data=dl_md,
        file_name=dl_filename,
        mime="application/msword",
        use_container_width=True,
        key=f"_vpd_dl_{component}",
        help="Download the complete prompt + metadata as a Word file.",
    )

    if _ac2.button(
        "✏️ Edit Prompt",
        key=f"_vpd_edit_{component}",
        use_container_width=True,
        help="Close this view and open the inline edit panel.",
    ):
        st.session_state[edit_session_key] = True
        st.rerun()   # closes the dialog; edit panel opens on the next render

    if _ac3.button(
        "✕ Close",
        key=f"_vpd_close_{component}",
        use_container_width=True,
        type="primary",
    ):
        st.rerun()


def _improve_prompt_with_llm(cur_sys: str, cur_usr: str, instructions: str, model_choice: str) -> dict:
    """Call the active LLM to improve an existing prompt.

    Returns a dict with keys ``system_prompt`` and ``user_prompt_template``.
    Falls back to the originals on any failure so the caller always gets a dict.
    """
    _IMPROVE_SYSTEM = (
        "You are an expert prompt engineer specialising in instructional design AI systems. "
        "Your task is to improve an existing LLM prompt based on user feedback. "
        "Preserve all placeholder variables (e.g. {course_title}, {topic}). "
        "Return ONLY valid JSON with exactly two keys: "
        "\"system_prompt\" and \"user_prompt_template\". No markdown, no explanation."
    )
    _IMPROVE_USER = (
        "CURRENT SYSTEM PROMPT:\n{sys}\n\n"
        "CURRENT USER PROMPT TEMPLATE:\n{usr}\n\n"
        "IMPROVEMENT INSTRUCTIONS:\n{instr}\n\n"
        "Return the improved prompts as JSON:\n"
        "{{\"system_prompt\": \"...\", \"user_prompt_template\": \"...\"}}"
    ).format(sys=cur_sys[:1200], usr=cur_usr[:1200], instr=instructions)

    try:
        from promptops_app.services.llm_service import generate_text as _call
        from promptops_app.core.llm_client import safe_json_loads
        raw = _call(model_choice, _IMPROVE_SYSTEM, _IMPROVE_USER)
        if isinstance(raw, str) and raw.startswith("ERROR"):
            raise ValueError(raw)
        parsed = safe_json_loads(raw)
        if isinstance(parsed, dict) and ("system_prompt" in parsed or "user_prompt_template" in parsed):
            return {
                "system_prompt":        parsed.get("system_prompt", cur_sys),
                "user_prompt_template": parsed.get("user_prompt_template", cur_usr),
            }
        raise ValueError("Unexpected response shape")
    except Exception:
        return {"system_prompt": cur_sys, "user_prompt_template": cur_usr}


# ---------------------------------------------------------------------------
# Main component
# ---------------------------------------------------------------------------

def render_inline_prompt_controls(
    db,
    component: str,
    project_id: Optional[int],
    cluster_id: Optional[int],
    course_id: Optional[int],
    user_name: str,
    model_choice: str,
    default_system: str = "",
    default_user: str = "",
    extra_placeholder: str = "e.g. Focus on clinical simulations. Add DEI examples.",
    project_name: str = "",
    cluster_name: str = "",
    course_name: str = "",
    user_role: str = "author",
    show_extra_instructions: bool = True,
    show_save_btn: bool = True,
) -> tuple[str, str, str]:
    """Render inline prompt controls and return (system_prompt, user_prompt_template, extra_instructions).

    Place this call OUTSIDE any ``st.form``, directly above the Generate button.
    All action buttons (Create, Edit, Improve, Save, Download) work without form constraints.

    Parameters
    ----------
    user_role:
        DB role string — ``"admin"``, ``"reviewer"`` (Lead), or ``"author"`` (ID).
        Controls whether the selector is editable and whether the Fix panel is shown.
    """
    _PFX            = f"_gc_{component}"
    _SEL_KEY        = f"{_PFX}_sel"
    _EXTRA_KEY      = f"{_PFX}_extra"
    _AI_KEY         = f"{_PFX}_ai_sugg"
    _INSTR_SEL      = f"{_PFX}_instr_sel"
    _SHOW_CREATE    = f"{_PFX}_show_create"
    _SHOW_EDIT      = f"{_PFX}_show_edit"
    _SHOW_IMPR      = f"{_PFX}_show_improve"
    _SHOW_SAVE      = f"{_PFX}_show_save"
    _SHOW_NEW_ASSET = f"{_PFX}_show_new_asset"
    _SHOW_FIX       = f"{_PFX}_show_fix"
    _OVRD_SYS       = f"{_PFX}_override_sys"   # "Use Now" overrides — not persisted to DB
    _OVRD_USR       = f"{_PFX}_override_usr"
    _DB_SAVED_SEL   = f"{_PFX}_db_saved_sel"   # tracks last label persisted to DB (Priority 4)

    _is_admin        = user_role == "admin"
    _is_lead         = user_role == "reviewer"
    _can_manage_fix  = _is_admin or _is_lead

    # ── Load prompt assets — strict component filter ───────────────────────────
    # Only prompts whose component_type matches this tab are shown.
    # Previous code also loaded cross-tagged + all-remaining prompts, which caused
    # every component's prompts to appear in every tab's selector.
    all_prompts: list[Prompt] = prompt_repository.list_prompts_by_component(db, component)

    if not all_prompts:
        if _EXTRA_KEY not in st.session_state:
            st.session_state[_EXTRA_KEY] = ""
        return default_system, default_user, st.session_state.get(_EXTRA_KEY, "")

    opt_labels: list[str]              = []
    label_to_prompt: dict[str, Prompt] = {}
    for p in all_prompts:
        lbl = _display_label(p)
        if lbl in label_to_prompt:
            lbl = f"{lbl} ({p.id})"
        opt_labels.append(lbl)
        label_to_prompt[lbl] = p

    # ── Resolve any scope-fixed prompt ───────────────────────────────────────
    _fixing      = prompt_repository.resolve_fixed_prompt(
        db, component,
        project_id=project_id, cluster_id=cluster_id, course_id=course_id,
    )
    _fixed_p: Prompt | None = None
    _fixed_role_label       = ""
    if _fixing and _fixing.prompt_id:
        _fixed_p = db.query(Prompt).filter(Prompt.id == _fixing.prompt_id).first()
        if _fixed_p and _display_label(_fixed_p) not in label_to_prompt:
            # Fixed prompt exists but belongs to a different component — ignore
            _fixed_p = None
        if _fixed_p:
            _fixed_role_label = "Admin" if _fixing.fixed_by_role == "admin" else "Lead"

    # Selector is read-only for authors/IDs when a prompt is fixed
    _selector_locked = bool(_fixed_p and not _can_manage_fix)

    # ── Auto-select — full 5-level priority chain ─────────────────────────────
    #
    #   1. Course-level fixed prompt   ┐
    #   2. Cluster-level fixed prompt  ├─ resolved by resolve_fixed_prompt()
    #   3. Project-level fixed prompt  ┘
    #   4. User's last selected prompt   (DB-persisted via UserPromptPreference)
    #   5. Component default prompt      (is_default=True for this component_type)
    #
    saved_label = st.session_state.get(_SEL_KEY)   # current in-session selection

    if _fixed_p:
        # Priorities 1–3: a scope-fixed prompt exists
        _fixed_lbl = _display_label(_fixed_p)
        if not _can_manage_fix:
            # Authors/IDs: always land on the fixed prompt; cannot override
            saved_label = _fixed_lbl
            st.session_state[_SEL_KEY] = _fixed_lbl
        elif saved_label not in label_to_prompt:
            # Admin/Lead: default to fixed on first open; they can still switch per-session
            saved_label = _fixed_lbl
    elif saved_label not in label_to_prompt:
        # Priority 4: user's last DB-persisted selection for this component+course
        _pref_p = prompt_repository.get_user_prompt_preference(
            db, user_name, component, course_id
        )
        if _pref_p:
            _pref_lbl = _display_label(_pref_p)
            if _pref_lbl in label_to_prompt:
                saved_label = _pref_lbl

        if saved_label not in label_to_prompt:
            # Priority 5: system-seeded default for this component_type
            _def = prompt_repository.get_default_prompt(db, component)
            if _def:
                saved_label = _display_label(_def)
            elif opt_labels:
                saved_label = opt_labels[0]

    if _EXTRA_KEY not in st.session_state:
        st.session_state[_EXTRA_KEY] = ""

    saved_instrs = list_latest_for_component(
        db, component=component, project_id=project_id, course_id=course_id
    )

    # ── Section header ────────────────────────────────────────────────────────
    _header_labels = {
        "cdd": "CDD Prompt Library",
        "blueprint": "Blueprint Prompt Library",
        "generation": "Generation Prompt Library",
        "style": "Style Prompt Library",
    }
    _header_text = _header_labels.get(component, f"{component.upper()} Prompt Library")
    st.markdown(
        f"<div style='font-size:0.9rem;font-weight:700;text-transform:uppercase;"
        f"letter-spacing:.09em;color:#4f46e5;margin:10px 0 6px;'>🎯 {_header_text}</div>",
        unsafe_allow_html=True,
    )

    # ── Prompt template selector + View button ────────────────────────────────
    _sel_col, _view_col = st.columns([0.82, 0.18])

    with _sel_col:
        sel_label: str = st.selectbox(
            "Prompt Template",
            opt_labels,
            index=opt_labels.index(saved_label) if saved_label in opt_labels else 0,
            key=_SEL_KEY,
            disabled=_selector_locked,
            help=(
                "**🏷️ Default** = system-seeded prompt.  "
                "Edits always create a new version — v1 is preserved."
                + ("  \n**🔒 Locked** — this prompt has been fixed by an Admin or Lead "
                   "and cannot be changed." if _selector_locked else "")
            ),
        )

    sel_p: Prompt = label_to_prompt[sel_label]
    sel_ver: PromptVersion | None = prompt_repository.get_active_version(db, sel_p.id)

    cur_sys: str = (sel_ver.system_prompt          or default_system) if sel_ver else default_system
    cur_usr: str = (sel_ver.user_prompt_template   or default_user)   if sel_ver else default_user

    # ── Persist Priority-4 preference (user's last selection) ────────────────
    # We compare against _DB_SAVED_SEL (the last label we wrote to the DB in THIS
    # session) to avoid a DB write on every rerun.  We skip saving when the
    # selector is locked (i.e. the selection was forced by a scope fix, not the
    # user's own choice).
    if (
        not _selector_locked
        and sel_label != st.session_state.get(_DB_SAVED_SEL)
    ):
        try:
            prompt_repository.save_user_prompt_preference(
                db,
                user_name=user_name,
                component=component,
                course_id=course_id,
                prompt_id=sel_p.id,
                project_id=project_id,
            )
            st.session_state[_DB_SAVED_SEL] = sel_label
        except Exception:
            pass   # preference save must never block generation

    # Metadata badge — rendered below the selector, inside the left column
    _meta = [f"📦 **{sel_p.name}**", f"v`{sel_p.active_version or '—'}`"]
    if sel_p.is_default:
        _meta.append("🏷️ `default`")
    if sel_p.owner:
        _meta.append(f"owner: `{sel_p.owner}`")
    if sel_p.updated_at:
        try:
            _meta.append(f"updated: `{sel_p.updated_at.strftime('%Y-%m-%d')}`")
        except Exception:
            pass
    with _sel_col:
        st.caption("  ·  ".join(_meta))

    # ── 👁 View Prompt button (right column, aligned with selectbox) ──────────
    with _view_col:
        # A small top-margin matches the label height that Streamlit adds above
        # every input widget so the button sits at the same vertical centre.
        st.markdown("<div style='height:1.78rem;'></div>", unsafe_allow_html=True)
        if st.button(
            "👁 View",
            key=f"{_PFX}_btn_view",
            use_container_width=True,
            help="Preview the complete prompt template, metadata, and current instructions.",
        ):
            _is_ai_ov   = _OVRD_SYS in st.session_state or _OVRD_USR in st.session_state
            _view_sys   = st.session_state.get(_OVRD_SYS, cur_sys)
            _view_usr   = st.session_state.get(_OVRD_USR, cur_usr)
            _view_extra = st.session_state.get(_EXTRA_KEY, "")
            _safe_ver   = (sel_p.active_version or "v1").replace("/", "-").replace(" ", "_")
            _prompt_viewer_dialog(
                component=component,
                prompt_name=sel_p.name,
                prompt_version=sel_p.active_version or "v1",
                prompt_owner=sel_p.owner or "—",
                prompt_updated=sel_p.updated_at,
                is_default=sel_p.is_default,
                project_name=project_name,
                cluster_name=cluster_name,
                course_name=course_name,
                system_prompt=_view_sys,
                user_prompt=_view_usr,
                extra_instructions=_view_extra,
                is_ai_override=_is_ai_ov,
                edit_session_key=_SHOW_EDIT,
                dl_md=_build_prompt_md(
                    project_name=project_name,
                    cluster_name=cluster_name,
                    course_name=course_name,
                    component=component,
                    prompt_name=sel_p.name,
                    prompt_version=sel_p.active_version or "v1",
                    system_prompt=_view_sys,
                    user_prompt_template=_view_usr,
                    extra_instructions=_view_extra,
                    is_ai_override=_is_ai_ov,
                ),
                dl_filename=f"prompt_{component}_{_safe_ver}.doc",
            )

    # ── Fixed-prompt indicator ────────────────────────────────────────────────
    # Shown to everyone when a prompt is fixed; admin/lead also get Fix/Unfix controls.
    if _fixed_p:
        if _selector_locked:
            # Author/ID view — read-only notice
            st.markdown(
                f"<div style='background:#fff7ed;border:1.5px solid #fb923c;"
                f"border-radius:8px;padding:7px 12px;font-size:0.8rem;color:#92400e;"
                f"display:flex;align-items:center;gap:8px;margin-top:4px;'>"
                f"<span style='font-size:1rem;'>📌</span>"
                f"<div><strong>Fixed by {_fixed_role_label}:</strong> "
                f"<em>{_fixed_p.name}</em> &nbsp;·&nbsp; scope: "
                f"<code style='background:#fed7aa;padding:1px 5px;border-radius:4px;'>"
                f"{_fixing.scope_level}</code></div>"
                f"</div>",
                unsafe_allow_html=True,
            )
        else:
            # Admin/Lead view — notice + Unfix button inline
            _fi_c1, _fi_c2 = st.columns([0.78, 0.22])
            _fi_c1.markdown(
                f"<div style='background:#fef9c3;border:1.5px solid #fde047;"
                f"border-radius:8px;padding:6px 12px;font-size:0.78rem;color:#78350f;"
                f"display:flex;align-items:center;gap:7px;'>"
                f"<span>📌</span>"
                f"<span><strong>Fixed by {_fixed_role_label}:</strong> "
                f"<em>{_fixed_p.name}</em> · scope: <code style='background:#fef08a;"
                f"padding:1px 5px;border-radius:4px;'>{_fixing.scope_level}</code>"
                f"<br><span style='font-size:0.72rem;color:#92400e;'>"
                f"You can still change the selection for this session.</span></span>"
                f"</div>",
                unsafe_allow_html=True,
            )
            if _fi_c2.button("🔓 Unfix", key=f"{_PFX}_unfix_quick",
                             use_container_width=True,
                             help=f"Remove the fix for scope '{_fixing.scope_level}'."):
                prompt_repository.unset_fixed_prompt(
                    db,
                    component=component,
                    scope_level=_fixing.scope_level,
                    project_id=_fixing.project_id,
                    cluster_id=_fixing.cluster_id,
                    course_id=_fixing.course_id,
                )
                st.toast(f"🔓 Prompt fix removed for scope '{_fixing.scope_level}'.")
                st.rerun()

    # Admin/Lead: Fix panel (toggle) — shown even when nothing is currently fixed
    if _can_manage_fix:
        if st.button(
            "📌 Fix Prompt for a Scope",
            key=f"{_PFX}_btn_fix",
            use_container_width=False,
            help="Lock the currently selected prompt as the default for a project/cluster/course scope.",
        ):
            st.session_state[_SHOW_FIX] = not st.session_state.get(_SHOW_FIX, False)
            st.rerun()

        if st.session_state.get(_SHOW_FIX):
            with st.container():
                st.markdown(
                    "<div style='background:#f0f9ff;border:1.5px solid #7dd3fc;"
                    "border-radius:10px;padding:12px 16px;margin:6px 0;'>"
                    "<div style='font-size:0.78rem;font-weight:700;color:#0369a1;"
                    "margin-bottom:8px;'>📌 Fix <em>\"" + sel_p.name + "\"</em> as the "
                    "default prompt for a scope</div>"
                    "<div style='font-size:0.74rem;color:#0c4a6e;'>"
                    "All users at the chosen scope will see this prompt pre-selected "
                    "and locked. Admins and Leads can still change it per-session.</div>"
                    "</div>",
                    unsafe_allow_html=True,
                )
                # Build scope options based on available IDs and user role
                _scope_opts: list[tuple[str, str, int | None, int | None, int | None]] = []
                if course_id:
                    _scope_opts.append((f"This Course (id {course_id})", "course",
                                        project_id, cluster_id, course_id))
                if cluster_id:
                    _scope_opts.append((f"This Cluster (id {cluster_id})", "cluster",
                                        project_id, cluster_id, None))
                if project_id:
                    _scope_opts.append((f"This Project (id {project_id})", "project",
                                        project_id, None, None))

                if not _scope_opts:
                    st.info("Open a project / cluster / course first to use scoped fixing.")
                else:
                    _fix_c1, _fix_c2, _fix_c3 = st.columns([0.52, 0.24, 0.24])
                    _scope_labels = [o[0] for o in _scope_opts]
                    _scope_sel_lbl = _fix_c1.selectbox(
                        "Scope",
                        _scope_labels,
                        key=f"{_PFX}_fix_scope_sel",
                        label_visibility="collapsed",
                    )
                    _chosen = next(o for o in _scope_opts if o[0] == _scope_sel_lbl)
                    _, _ch_level, _ch_pid, _ch_cid, _ch_crsid = _chosen

                    if _fix_c2.button("📌 Fix", key=f"{_PFX}_fix_confirm",
                                      use_container_width=True, type="primary"):
                        prompt_repository.set_fixed_prompt(
                            db,
                            component=component,
                            scope_level=_ch_level,
                            project_id=_ch_pid,
                            cluster_id=_ch_cid,
                            course_id=_ch_crsid,
                            prompt_id=sel_p.id,
                            fixed_by=user_name,
                            fixed_by_role=user_role,
                        )
                        st.session_state[_SHOW_FIX] = False
                        st.toast(f"✅ '{sel_p.name}' fixed for {_scope_sel_lbl}.")
                        st.rerun()

                    if _fix_c3.button("✕ Cancel", key=f"{_PFX}_fix_cancel",
                                      use_container_width=True):
                        st.session_state[_SHOW_FIX] = False
                        st.rerun()

    # ── "Use Now" override indicator ──────────────────────────────────────────
    _has_override = _OVRD_SYS in st.session_state or _OVRD_USR in st.session_state
    if _has_override:
        _ov1, _ov2 = st.columns([0.8, 0.2])
        _ov1.markdown(
            "<div style='background:#eff6ff;border:1.5px solid #93c5fd;border-radius:8px;"
            "padding:7px 12px;font-size:0.82rem;color:#1d4ed8;'>"
            "🤖 <strong>AI-improved prompt active</strong> — used for this generation only. "
            "Not saved to the database.</div>",
            unsafe_allow_html=True,
        )
        if _ov2.button("↩️ Revert", key=f"{_PFX}_ovrd_clear", use_container_width=True,
                       help="Restore the saved DB prompt for generation."):
            st.session_state.pop(_OVRD_SYS, None)
            st.session_state.pop(_OVRD_USR, None)
            st.rerun()

    # ── AI suggestion panel ───────────────────────────────────────────────────
    _ai_sugg: dict = st.session_state.get(_AI_KEY, {})
    if _ai_sugg:
        st.markdown(
            "<div style='background:#f0fdf4;border:1.5px solid #86efac;border-radius:10px;"
            "padding:10px 16px;margin:8px 0 4px;'>"
            "<div style='font-size:0.78rem;font-weight:700;color:#166534;margin-bottom:6px;'>"
            "✨ AI Improvement Ready — edit if needed, then choose an action</div>"
            "<div style='font-size:0.75rem;color:#6b7280;'>Changes are NOT saved unless you "
            "explicitly click Save or Use. The original prompt is always preserved.</div>"
            "</div>",
            unsafe_allow_html=True,
        )

        # Editable text areas — user can tweak the suggestion before acting
        _sugg_sys_key = f"{_PFX}_ai_edit_sys"
        _sugg_usr_key = f"{_PFX}_ai_edit_usr"

        # Seed the editable areas from the suggestion on first render
        if _sugg_sys_key not in st.session_state:
            st.session_state[_sugg_sys_key] = _ai_sugg.get("system_prompt", cur_sys)
        if _sugg_usr_key not in st.session_state:
            st.session_state[_sugg_usr_key] = _ai_sugg.get("user_prompt_template", cur_usr)

        _ae1, _ae2 = st.columns(2)
        with _ae1:
            st.markdown(
                "<span style='font-size:0.76rem;font-weight:600;color:#374151;'>"
                "System Prompt</span>",
                unsafe_allow_html=True,
            )
            _edit_sys: str = st.text_area(
                "Suggested System Prompt",
                height=180,
                label_visibility="collapsed",
                key=_sugg_sys_key,
            )
        with _ae2:
            st.markdown(
                "<span style='font-size:0.76rem;font-weight:600;color:#374151;'>"
                "User Prompt Template</span>",
                unsafe_allow_html=True,
            )
            _edit_usr: str = st.text_area(
                "Suggested User Prompt Template",
                height=180,
                label_visibility="collapsed",
                key=_sugg_usr_key,
            )

        # ── Four action buttons ───────────────────────────────────────────────
        _ab1, _ab2, _ab3, _ab4 = st.columns(4)

        # 1. Use for this generation only (no DB write)
        if _ab1.button(
            "✅ Use Now",
            key=f"{_PFX}_ai_use_now",
            use_container_width=True,
            type="primary",
            help="Use the improved prompt for this generation only — not saved to the database.",
        ):
            st.session_state[_OVRD_SYS] = _edit_sys
            st.session_state[_OVRD_USR] = _edit_usr
            # Clear suggestion + seeded edit keys so next Improve starts fresh
            for _k in (_AI_KEY, _sugg_sys_key, _sugg_usr_key):
                st.session_state.pop(_k, None)
            st.toast("✅ AI-improved prompt will be used for this generation.")
            st.rerun()

        # 2. Save as new version of the current prompt
        if _ab2.button(
            "💾 Save as Version",
            key=f"{_PFX}_ai_save_ver",
            use_container_width=True,
            help=f"Save as a new version of '{sel_p.name}' and activate it.",
        ):
            _nv_count = len(prompt_repository.list_versions_for_prompt(db, sel_p.id))
            _nv_tag   = f"v{_nv_count + 1}-ai"
            prompt_repository.deploy_new_version(
                db, sel_p, _edit_sys, _edit_usr,
                _nv_tag, "AI-improved via inline controls.", user_name,
            )
            for _k in (_AI_KEY, _sugg_sys_key, _sugg_usr_key):
                st.session_state.pop(_k, None)
            st.toast(f"✅ Saved as {_nv_tag} for '{sel_p.name}'")
            st.rerun()

        # 3. Save as a brand-new prompt asset
        if _ab3.button(
            "📁 Save as New Asset",
            key=f"{_PFX}_ai_save_asset",
            use_container_width=True,
            help="Create a new prompt asset from the improved version.",
        ):
            st.session_state[_SHOW_NEW_ASSET] = True
            st.rerun()

        # 4. Discard suggestion
        if _ab4.button(
            "🗑️ Discard",
            key=f"{_PFX}_ai_discard",
            use_container_width=True,
            help="Discard the AI suggestion — original prompt is unchanged.",
        ):
            for _k in (_AI_KEY, _sugg_sys_key, _sugg_usr_key, _SHOW_NEW_ASSET):
                st.session_state.pop(_k, None)
            st.rerun()

        # ── Save as New Asset panel ───────────────────────────────────────────
        if st.session_state.get(_SHOW_NEW_ASSET):
            st.markdown("**Name the new prompt asset:**")
            _na1, _na2, _na3 = st.columns([0.45, 0.35, 0.20])
            _na_name = _na1.text_input(
                "Asset name *",
                placeholder=f"e.g. improved_{component}_prompt",
                key=f"{_PFX}_ai_asset_name",
                label_visibility="collapsed",
            )
            _na_desc = _na2.text_input(
                "Description",
                placeholder="AI-improved version",
                key=f"{_PFX}_ai_asset_desc",
                label_visibility="collapsed",
            )
            if _na3.button("🚀 Create", key=f"{_PFX}_ai_asset_create", use_container_width=True, type="primary"):
                if not _na_name.strip():
                    st.error("Asset name is required.")
                elif prompt_repository.get_prompt_by_name(db, _na_name.strip()):
                    st.error(f"**'{_na_name.strip()}'** already exists — choose a unique name.")
                else:
                    _p_new = Prompt(
                        name=_na_name.strip(),
                        description=_na_desc.strip() or f"AI-improved {component} prompt",
                        owner=user_name,
                        active_version="v1",
                        tags=component,
                        component_type=component,
                        is_default=False,
                        created_at=datetime.utcnow(),
                        updated_at=datetime.utcnow(),
                    )
                    db.add(_p_new); db.commit(); db.refresh(_p_new)
                    db.add(PromptVersion(
                        prompt_id=_p_new.id, version="v1", version_number=1,
                        system_prompt=_edit_sys,
                        user_prompt_template=_edit_usr,
                        change_reason="Created from AI improvement.",
                        is_active=True, created_by=user_name,
                    ))
                    db.commit()
                    st.session_state[_SEL_KEY] = _na_name.strip()
                    for _k in (_AI_KEY, _sugg_sys_key, _sugg_usr_key, _SHOW_NEW_ASSET):
                        st.session_state.pop(_k, None)
                    st.success(f"✅ **'{_na_name.strip()}'** created and activated!")
                    st.rerun()

    # ── Additional instructions ───────────────────────────────────────────────
    if show_extra_instructions:
        st.markdown(
            "<div style='font-size:0.8rem;font-weight:600;color:#374151;margin-top:10px;margin-bottom:2px;'>"
            "💬 Additional Instructions "
            "<span style='font-weight:400;font-size:0.75rem;color:#9ca3af;'>(optional)</span>"
            "</div>",
            unsafe_allow_html=True,
        )

        # Compact saved-instructions loader
        if saved_instrs:
            _il1, _il2 = st.columns([0.75, 0.25])
            _instr_opts = ["— Start fresh —"] + [r.name for r in saved_instrs]
            _instr_map  = {r.name: r for r in saved_instrs}
            _sel_instr  = _il1.selectbox(
                "Saved instructions",
                _instr_opts,
                key=_INSTR_SEL,
                label_visibility="collapsed",
            )
            if _il2.button("📥 Load", key=f"{_PFX}_load_instr", use_container_width=True):
                if _sel_instr != "— Start fresh —":
                    _rec = _instr_map.get(_sel_instr)
                    if _rec:
                        st.session_state[_EXTRA_KEY] = _rec.content
                        st.rerun()
                else:
                    st.session_state[_EXTRA_KEY] = ""
                    st.rerun()

        extra_instr: str = st.text_area(
            "Additional Instructions",
            placeholder=extra_placeholder,
            height=90,
            label_visibility="collapsed",
            key=_EXTRA_KEY,
        )
    else:
        # Textarea rendered externally (e.g. in CDD/Blueprint left column).
        # Read the current value from session state without rendering a duplicate widget.
        extra_instr = st.session_state.get(_EXTRA_KEY, "")

    # ── Action buttons — two rows so labels stay readable in narrow columns ──────
    # Row 1 — primary prompt actions (used most often)
    _br1, _br2 = st.columns(2)

    if _br1.button(
        "🤖 Improve with AI",
        key=f"{_PFX}_btn_impr",
        use_container_width=True,
        help="Use AI to rewrite the selected prompt based on your instructions.",
    ):
        st.session_state[_SHOW_IMPR]   = not st.session_state.get(_SHOW_IMPR, False)
        st.session_state[_SHOW_CREATE] = False
        st.session_state[_SHOW_EDIT]   = False
        st.rerun()

    if show_save_btn:
        if _br2.button(
            "💾 Save Instructions",
            key=f"{_PFX}_btn_save",
            use_container_width=True,
            help="Save the current Additional Instructions text for reuse across generations.",
        ):
            st.session_state[_SHOW_SAVE] = not st.session_state.get(_SHOW_SAVE, False)
            st.rerun()

    # Row 2 — asset management + download (lighter-weight; less frequently used)
    _br3, _br4, _br5 = st.columns(3)

    if _br3.button(
        "➕ New Prompt",
        key=f"{_PFX}_btn_new",
        use_container_width=True,
        help="Create a new custom prompt asset for this component.",
    ):
        st.session_state[_SHOW_CREATE] = not st.session_state.get(_SHOW_CREATE, False)
        st.session_state[_SHOW_EDIT]   = False
        st.session_state[_SHOW_IMPR]   = False
        st.rerun()

    if _br4.button(
        "✏️ Edit Prompt",
        key=f"{_PFX}_btn_edit",
        use_container_width=True,
        help="Edit the selected prompt template and save as a new version.",
    ):
        st.session_state[_SHOW_EDIT]   = not st.session_state.get(_SHOW_EDIT, False)
        st.session_state[_SHOW_CREATE] = False
        st.session_state[_SHOW_IMPR]   = False
        st.rerun()

    # ⬇️ Download — prompt + instructions as Markdown
    _dl_md = _build_prompt_md(
        project_name=project_name,
        cluster_name=cluster_name,
        course_name=course_name,
        component=component,
        prompt_name=sel_p.name,
        prompt_version=sel_p.active_version or "v1",
        system_prompt=st.session_state.get(_OVRD_SYS, cur_sys),
        user_prompt_template=st.session_state.get(_OVRD_USR, cur_usr),
        extra_instructions=st.session_state.get(_EXTRA_KEY, ""),
        is_ai_override=_has_override,
    )
    _safe_ver = (sel_p.active_version or "v1").replace("/", "-").replace(" ", "_")
    _br5.download_button(
        "⬇️ Download",
        data=_dl_md,
        file_name=f"prompt_{component}_{_safe_ver}.doc",
        mime="application/msword",
        use_container_width=True,
        key=f"{_PFX}_btn_dl",
        help="Download the active prompt + your instructions as a Word file.",
    )

    # ── Save instructions panel ───────────────────────────────────────────────
    if show_save_btn and st.session_state.get(_SHOW_SAVE):
        with st.container():
            st.caption("**Name and save the current instructions for reuse:**")
            _sn1, _sn2, _sn3 = st.columns([0.48, 0.26, 0.26])
            _save_name = _sn1.text_input(
                "Name",
                placeholder="e.g. Clinical simulation focus",
                key=f"{_PFX}_save_name",
                label_visibility="collapsed",
            )
            _as_new = _sn2.checkbox("New version", key=f"{_PFX}_save_nv",
                                    help="Keep previous save and create a new version.")
            if _sn3.button("Confirm", key=f"{_PFX}_save_ok", use_container_width=True):
                if _save_name.strip() and extra_instr.strip():
                    _save_instr(
                        db,
                        name=_save_name.strip(),
                        component=component,
                        content=extra_instr.strip(),
                        project_id=project_id,
                        cluster_id=cluster_id,
                        course_id=course_id,
                        created_by=user_name,
                        as_new_version=_as_new,
                    )
                    st.success(f"✅ Saved as **'{_save_name.strip()}'**")
                    st.session_state[_SHOW_SAVE] = False
                    st.rerun()
                elif not extra_instr.strip():
                    st.warning("Write some instructions before saving.")
                else:
                    st.warning("Enter a name to save.")

    # ── Create New Prompt panel ───────────────────────────────────────────────
    if st.session_state.get(_SHOW_CREATE):
        with st.expander(f"➕ Create New {_COMP_LABELS.get(component, component)} Prompt", expanded=True):
            _cn_name = st.text_input(
                "Asset Name *", placeholder=f"e.g. custom_{component}_prompt",
                key=f"{_PFX}_cn_name",
            )
            _cn_desc = st.text_input("Description", placeholder="What is this prompt for?", key=f"{_PFX}_cn_desc")
            _cn_sys  = st.text_area("System Prompt", value=cur_sys, height=140, key=f"{_PFX}_cn_sys")
            _cn_usr  = st.text_area("User Prompt Template", value=cur_usr, height=140, key=f"{_PFX}_cn_usr")
            _cc1, _cc2 = st.columns(2)
            if _cc1.button("🚀 Create & Activate", key=f"{_PFX}_cn_save", use_container_width=True, type="primary"):
                if not _cn_name.strip():
                    st.error("Asset name is required.")
                elif prompt_repository.get_prompt_by_name(db, _cn_name.strip()):
                    st.error(f"**'{_cn_name.strip()}'** already exists — choose a unique name.")
                else:
                    _p_new = Prompt(
                        name=_cn_name.strip(),
                        description=_cn_desc.strip() or None,
                        owner=user_name,
                        active_version="v1",
                        tags=component,
                        component_type=component,
                        is_default=False,
                        created_at=datetime.utcnow(),
                        updated_at=datetime.utcnow(),
                    )
                    db.add(_p_new); db.commit(); db.refresh(_p_new)
                    db.add(PromptVersion(
                        prompt_id=_p_new.id, version="v1", version_number=1,
                        system_prompt=_cn_sys,
                        user_prompt_template=_cn_usr,
                        change_reason="Created via inline controls.",
                        is_active=True, created_by=user_name,
                    ))
                    db.commit()
                    st.session_state[_SEL_KEY]     = _cn_name.strip()
                    st.session_state[_SHOW_CREATE] = False
                    st.success(f"✅ **'{_cn_name.strip()}'** created and activated!")
                    st.rerun()
            if _cc2.button("✕ Cancel", key=f"{_PFX}_cn_cancel", use_container_width=True):
                st.session_state[_SHOW_CREATE] = False
                st.rerun()

    # ── Edit Prompt panel ─────────────────────────────────────────────────────
    if st.session_state.get(_SHOW_EDIT):
        _is_def = sel_p.is_default
        with st.expander(f"✏️ Edit: {sel_p.name}", expanded=True):
            if _is_def:
                st.info(
                    f"**{sel_p.name}** is the system default. "
                    "Your edits will be saved as a new version — v1 is preserved.",
                    icon="🏷️",
                )
            _ev_count = len(prompt_repository.list_versions_for_prompt(db, sel_p.id))
            _e_sys = st.text_area("System Prompt", value=cur_sys, height=160, key=f"{_PFX}_e_sys")
            _e_usr = st.text_area("User Prompt Template", value=cur_usr, height=160, key=f"{_PFX}_e_usr")
            _e_ver = st.text_input("Version Tag", value=f"v{_ev_count + 1}", key=f"{_PFX}_e_ver")
            _e_log = st.text_input("Change Log", placeholder="What changed?", key=f"{_PFX}_e_log")
            _ec1, _ec2 = st.columns(2)
            if _ec1.button("💾 Save as New Version", key=f"{_PFX}_e_save", use_container_width=True, type="primary"):
                if not _e_ver.strip():
                    st.error("Version tag is required.")
                else:
                    prompt_repository.deploy_new_version(
                        db, sel_p,
                        _e_sys, _e_usr,
                        _e_ver.strip(),
                        _e_log.strip() or "Edited via inline controls.",
                        user_name,
                    )
                    st.session_state[_SHOW_EDIT] = False
                    st.success(f"✅ Version **{_e_ver.strip()}** saved for **{sel_p.name}**.")
                    st.rerun()
            if _ec2.button("✕ Cancel", key=f"{_PFX}_e_cancel", use_container_width=True):
                st.session_state[_SHOW_EDIT] = False
                st.rerun()

    # ── Improve with AI panel ─────────────────────────────────────────────────
    if st.session_state.get(_SHOW_IMPR):
        with st.expander("🤖 Improve Prompt with AI", expanded=True):
            st.caption(
                "Describe how to improve the selected prompt template. "
                "The AI generates a revised system + user prompt — review before applying."
            )
            _imp_instr = st.text_area(
                "Improvement Instructions",
                placeholder=(
                    "e.g. Make the system prompt more concise.  "
                    "Emphasise real-world examples.  Remove jargon."
                ),
                height=80,
                key=f"{_PFX}_imp_instr",
            )
            if st.button("✨ Generate Improvement", key=f"{_PFX}_imp_run", use_container_width=True):
                if _imp_instr.strip():
                    with st.spinner("AI is improving your prompt…"):
                        _sugg = _improve_prompt_with_llm(cur_sys, cur_usr, _imp_instr, model_choice)
                    # Clear any stale editable-area keys so the panel seeds from the new suggestion
                    st.session_state.pop(f"{_PFX}_ai_edit_sys", None)
                    st.session_state.pop(f"{_PFX}_ai_edit_usr", None)
                    st.session_state[_AI_KEY]    = _sugg
                    st.session_state[_SHOW_IMPR] = False
                    st.rerun()
                else:
                    st.warning("Describe what you want to improve first.")

    # ── Resolve final prompts ─────────────────────────────────────────────────
    # "Use Now" sets a session-state override that lives until the user reverts.
    # It does NOT touch the DB — the saved prompt is always recoverable.
    _final_sys = st.session_state.get(_OVRD_SYS, cur_sys)
    _final_usr = st.session_state.get(_OVRD_USR, cur_usr)
    return _final_sys, _final_usr, extra_instr
