"""Add blocks.content_html + content_html_at (additive).

Stores an LMS-ready standalone HTML rendition of a block's markdown content,
generated by the Canvas HTML Lesson Generator when a block is published. The
IMSCC exporter prefers this rendition over on-the-fly markdown conversion.

Strictly additive: both columns are nullable with no server default; existing
rows keep NULL until their block is (re)published.
"""

import sqlalchemy as sa
from alembic import op

revision = "000100000007"
down_revision = "000100000006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("blocks", sa.Column("content_html", sa.Text(), nullable=True))
    op.add_column("blocks", sa.Column("content_html_at", sa.DateTime(), nullable=True))


def downgrade() -> None:
    op.drop_column("blocks", "content_html_at")
    op.drop_column("blocks", "content_html")
