/** Fallback CDD prompts when no prompt library assets exist (matches Streamlit inline defaults). */
export const CDD_DEFAULT_SYSTEM = `You are an experienced Instructional Designer, CTE expert, and SME for middle school CTE Career Pathways.
Create structured, standards-aligned Course Design Documents with clear learning objectives, module structure, and assessment guidance.`;

export const CDD_DEFAULT_USER = `Create a CTE Course Design Document (CDD) for the following:

Course Title: {course_title}
Target Audience: {target_audience}
Expert Domain: {expert_domain}
Audience Level: {audience_level}
Estimated Duration: {estimated_duration} hours

{extra_instructions_block}

Use clear markdown headings. Include course details, module structure, and assessments.`;

export const BLUEPRINT_DEFAULT_SYSTEM = `You are an expert Instructional Designer developing a module-level blueprint derived from an approved CTE Curriculum Design Document (CDD).
Generate the blueprint ONLY for the selected module. Use the CDD as the single source of truth.`;

export const GENERATE_DEFAULT_SYSTEM = `You are an expert instructional content author. Generate high-quality, structured learning content aligned to the course blueprint and design document.`;

export const GENERATE_DEFAULT_USER = `Generate content for the selected component using the injected CDD and Blueprint context.

{extra_instructions_block}`;

export const BLUEPRINT_DEFAULT_USER = `Create a detailed module blueprint based on the CDD context below.

**CDD Context:**
{cdd_context}

**Selected Module:** {selected_module}

{extra_instructions_block}`;

export const COMPONENT_LABELS = {
  cdd: 'CDD',
  blueprint: 'Blueprint',
  generate: 'Generate',
  style: 'Style',
};

export function promptDisplayLabel(prompt) {
  if (prompt?.is_default) {
    const comp = COMPONENT_LABELS[prompt.component_type] || prompt.component_type || 'Prompt';
    return `🏷️ Default ${comp} Prompt`;
  }
  return prompt?.name || 'Unnamed prompt';
}

export function buildPromptDownloadMd({
  projectName,
  clusterName,
  courseName,
  component,
  promptName,
  promptVersion,
  systemPrompt,
  userPromptTemplate,
  extraInstructions,
  isAiOverride,
}) {
  const compLabel = COMPONENT_LABELS[component] || component;
  const lines = [
    `# Prompt Download — ${compLabel}`,
    '',
    `| Field | Value |`,
    `|---|---|`,
    `| **Project** | ${projectName || '—'} |`,
  ];
  if (clusterName) lines.push(`| **Cluster** | ${clusterName} |`);
  if (courseName) lines.push(`| **Title** | ${courseName} |`);
  lines.push(
    `| **Component** | ${compLabel} |`,
    `| **Prompt Asset** | ${promptName || '—'} |`,
    `| **Version** | ${promptVersion || '—'}${isAiOverride ? ' *(AI-improved — not saved)*' : ''} |`,
    '',
    '---',
    '',
    '## System Prompt',
    '',
    systemPrompt?.trim() || '*(none)*',
    '',
    '---',
    '',
    '## User Prompt Template',
    '',
    userPromptTemplate?.trim() || '*(none)*',
  );
  if (extraInstructions?.trim()) {
    lines.push('', '---', '', '## Additional Instructions', '', extraInstructions.trim());
  }
  lines.push('', '---', '', '*Generated by Content AI Studio*');
  return lines.join('\n');
}
